---
# tasks file for mysql

- import_tasks: opt_mysql.yml

- import_tasks: pre_mysql.yml

- import_tasks: build_mysql.yml

- import_tasks: install_mysql.yml

- import_tasks: init_mysql.yml

- import_tasks: test_mysql.yml 
